/* ************************************* */
/* ********       EXPORTS       ******** */
/* ************************************* */
export default {
    SEARCH_PRACTICE_CONTEXTS: { type: 'SEARCH_PRACTICE_CONTEXTS' },
    SEARCH_PRACTICE_CONTEXTS_FULFILLED: { type: 'SEARCH_PRACTICE_CONTEXTS_FULFILLED' },
    SEARCH_PRACTICE_CONTEXTS_REJECTED: { type: 'SEARCH_PRACTICE_CONTEXTS_REJECTED' },

    CLOSE_PRACTICE_CONTEXTS_POPIN: { type: 'CLOSE_PRACTICE_CONTEXTS_POPIN' },

    GET_ACTIVITY_REFERENCES: { type: 'GET_ACTIVITY_REFERENCES' },
    GET_ACTIVITY_REFERENCES_PENDING: { type: 'GET_ACTIVITY_REFERENCES_PENDING' },
    GET_ACTIVITY_REFERENCES_FULFILLED: { type: 'GET_ACTIVITY_REFERENCES_FULFILLED' },
    GET_ACTIVITY_REFERENCES_REJECTED: { type: 'GET_ACTIVITY_REFERENCES_REJECTED' },

    UPDATE_PRACTICE_CONTEXT: { type: 'UPDATE_PRACTICE_CONTEXT' },
    UPDATE_PRACTICE_CONTEXT_FULFILLED: { type: 'UPDATE_PRACTICE_CONTEXT_FULFILLED' },
    UPDATE_PRACTICE_CONTEXT_REJECTED: { type: 'UPDATE_PRACTICE_CONTEXT_REJECTED' },

    CHECK_PC_UNICITY: { type: 'CHECK_PC_UNICITY' },
    CHECK_PC_UNICITY_FULFILLED: { type: 'CHECK_PC_UNICITY_FULFILLED' },
    CHECK_PC_UNICITY_REJECTED: { type: 'CHECK_PC_UNICITY_REJECTED' },

    GET_COMMERCIAL_NETWORKS: { type: 'GET_COMMERCIAL_NETWORKS' },
    GET_COMMERCIAL_NETWORKS_PENDING: { type: 'GET_COMMERCIAL_NETWORKS_PENDING' },
    GET_COMMERCIAL_NETWORKS_FULFILLED: { type: 'GET_COMMERCIAL_NETWORKS_FULFILLED' },
    GET_COMMERCIAL_NETWORKS_REJECTED: { type: 'GET_COMMERCIAL_NETWORKS_REJECTED' },
};
